#!/usr/bin/env python3
"""Add AIAST security labels and AI-Provenance resources to a trimmed bundle.

Marks a subset of whitelist-eligible resources (Observation, Condition,
DiagnosticReport, AllergyIntolerance, MedicationRequest) as AI-generated by
adding the AIAST meta.security label, then appends one AI-Provenance
resource per labeled resource, per the AI Transparency on FHIR IG's
AI-Provenance profile: agent.who references one of the given AI Devices,
entity.what references one of the given prompt DocumentReferences (both
as external references, never contained), and roughly
--verifier-fraction of the Provenances also get a human verifier agent
referencing the shared Practitioner.

Resource selection is a deterministic, seeded random sample from the
eligible pool (excluding anything already labeled, so the script is safe
to re-run/extend). Devices and prompts are assigned round-robin, in the
order given on the command line, over the selected resources in seeded-
shuffled order -- pass a value more than once to weight it (e.g.
`--prompt prompt-1 --prompt prompt-1 --prompt prompt-2` labels twice as
many resources with prompt-1 as with prompt-2).

Usage:
    python3 label_bundle.py --input TRIMMED.json --output LABELED.json \\
        --seed 7 --device ai-device-1 \\
        --prompt prompt-1 --prompt prompt-1 --prompt prompt-2 \\
        --count 4 --verifier-fraction 0.5

    # or select exact resources (bypasses --count/--fraction):
    python3 label_bundle.py --input TRIMMED.json --output LABELED.json \\
        --seed 7 --device ai-device-1 --prompt prompt-1 \\
        --resource Observation/abc123 --resource Condition/def456
"""
import argparse
import json
import random
from pathlib import Path

WHITELIST = {"Observation", "Condition", "DiagnosticReport", "AllergyIntolerance", "MedicationRequest"}

AIAST_SECURITY_LABEL = {
    "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationValue",
    "code": "AIAST",
    "display": "Artificial Intelligence asserted",
}

def is_labeled(resource):
    for label in resource.get("meta", {}).get("security", []):
        if label.get("code") == "AIAST":
            return True
    return False


def add_aiast_label(resource):
    resource.setdefault("meta", {})
    resource["meta"].setdefault("security", [])
    if not is_labeled(resource):
        resource["meta"]["security"].append(dict(AIAST_SECURITY_LABEL))


def build_provenance(resource, resource_type, device_id, prompt_id, practitioner_id, verifier, recorded):
    target_ref = f"{resource_type}/{resource['id']}"
    provenance_id = f"provenance-{resource['id']}"
    agents = []
    if verifier:
        agents.append({
            "type": {
                "coding": [{
                    "system": "http://terminology.hl7.org/CodeSystem/provenance-participant-type",
                    "code": "verifier",
                    "display": "Verifier",
                }]
            },
            "who": {"reference": f"Practitioner/{practitioner_id}"},
        })
    agents.append({
        "type": {
            "coding": [{
                "system": "http://terminology.hl7.org/CodeSystem/provenance-participant-type",
                "code": "author",
                "display": "Author",
            }]
        },
        "who": {"reference": f"Device/{device_id}"},
    })
    provenance = {
        "resourceType": "Provenance",
        "id": provenance_id,
        "meta": {"profile": ["http://hl7.org/fhir/uv/aitransparency/StructureDefinition/AI-Provenance"]},
        "target": [{"reference": target_ref}],
        "recorded": recorded,
        "reason": [{"coding": [{
            "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationValue",
            "code": "AIAST",
        }]}],
        "activity": {
            "coding": [{
                "system": "http://terminology.hl7.org/CodeSystem/v3-DataOperation",
                "code": "CREATE",
                "display": "create",
            }]
        },
        "agent": agents,
        "entity": [{
            "role": "derivation",
            "what": {"reference": f"DocumentReference/{prompt_id}"},
        }],
    }
    return {
        "fullUrl": f"Provenance/{provenance_id}",
        "resource": provenance,
        "request": {"method": "PUT", "url": f"Provenance/{provenance_id}"},
    }


def select_resources(entries, args, rng):
    already_labeled = {e["fullUrl"] for e in entries if is_labeled(e["resource"])}
    eligible = [
        e for e in entries
        if e["resource"]["resourceType"] in WHITELIST and e["fullUrl"] not in already_labeled
    ]

    if args.resource:
        wanted = set(args.resource)
        selected = [e for e in eligible if e["request"]["url"] in wanted]
        found = {e["request"]["url"] for e in selected}
        missing = wanted - found
        if missing:
            raise ValueError(f"--resource target(s) not eligible or not found: {sorted(missing)}")
        return selected

    shuffled = list(eligible)
    rng.shuffle(shuffled)

    if args.count is not None:
        n = args.count
    elif args.fraction is not None:
        n = round(args.fraction * len(shuffled))
    else:
        raise ValueError("one of --count, --fraction, or --resource is required")

    n = min(n, len(shuffled))
    return shuffled[:n]


def main():
    parser = argparse.ArgumentParser(
        description="Add AIAST labels + AI-Provenance to a subset of whitelist-eligible "
        "resources in a trimmed transaction bundle.",
    )
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--seed", required=True, type=int, help="RNG seed for deterministic selection")
    parser.add_argument("--device", action="append", required=True, help="AI Device id; repeat to weight round-robin")
    parser.add_argument("--prompt", action="append", required=True, help="prompt DocumentReference id; repeat to weight round-robin")
    parser.add_argument("--practitioner", default="practitioner-verifier", help="verifier Practitioner id")
    parser.add_argument("--count", type=int, help="number of resources to label")
    parser.add_argument("--fraction", type=float, help="fraction of eligible resources to label")
    parser.add_argument("--resource", action="append", help="explicit 'ResourceType/id' to label (repeatable); overrides --count/--fraction")
    parser.add_argument("--verifier-fraction", type=float, default=0.5, help="fraction of Provenances that also get a human verifier agent")
    parser.add_argument("--recorded", default="2026-06-15T00:00:00Z", help="Provenance.recorded timestamp to use (when the AI processing happened, not the clinical event date)")
    args = parser.parse_args()

    bundle = json.loads(args.input.read_text())
    entries = bundle["entry"]

    rng = random.Random(args.seed)
    selected = select_resources(entries, args, rng)

    new_entries = []
    for i, entry in enumerate(selected):
        resource = entry["resource"]
        resource_type = resource["resourceType"]
        device_id = args.device[i % len(args.device)]
        prompt_id = args.prompt[i % len(args.prompt)]
        verifier = rng.random() < args.verifier_fraction

        add_aiast_label(resource)
        new_entries.append(
            build_provenance(resource, resource_type, device_id, prompt_id, args.practitioner, verifier, args.recorded)
        )

    bundle["entry"].extend(new_entries)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(bundle, indent=2) + "\n")
    print(f"{args.output}: labeled {len(selected)} resources, added {len(new_entries)} Provenance entries")


if __name__ == "__main__":
    main()
